### ISSUE TITLE
English version for our website

### ISSUE THREAD

**Issue by filipenevola** [CodeFTW/website#1]
Hi, it is important to have a version of our website in English.

I think the English version can be a little different because we need to explain why we need do learn English (we are Portuguese speakers) but we also need to invite English speakers to join us.

Who wants to help with it?

cc @raonifst @pvmilreu

**Comment by pvmilreu** [comment]
How can I help? Can I suggest a translation of the current content? By email? @filipenevola

**Comment by filipenevola** [comment]
@pvmilreu you can fork this repository and duplicate the index.html to index-en.html and translate there, ok? If you need help let me know.

When you finish you can just submit a Pull Request using this new fork, a button will pop-up for you when you have changes in your fork. We can do that together also.

**Comment by raonifst** [comment]
Hi guys,

I've been really busy the last few days.  Sorry for the delay :) Is there
anything I can help?

**Comment by filipenevola** [comment]
We need to start :)

**Comment by filipenevola** [comment]
done by @tgmarinho
